### ISSUE TITLE
🐛 [Bug] Space management in search

### ISSUE THREAD

**Issue by Ilithy** [camarm-dev/remede#251]
### Describe the bug / Décrivez le bug
Hi;
When you search for a word in Remède, and you add a space _(before or after the searched word)_ Remède will not find the word, instead it will offer to make a request to add the word, is it possible to modify this?

Thank you very much.

### To Reproduce / Pour reproduire
Steps to reproduce the behavior / Les étapes pour reproduire le bug:
1. Go to Remède 
2. Click on search bar
3. Type any word with space before or after the searched word
4. note that Remède does not display the definition, and instead offers to make an addition request

### Expected behavior / Comportement attendu
"Remède" ignores unnecessary and/or erroneous spaces and offers the definition(s) of the word you are looking for..
_the best would be to add an option to ignore spaces when searching (for a single word)_

### Screenshots
![Screenshot_20241223-094323](https://github.com/user-attachments/assets/4b8d65a1-e3e5-4139-a9ee-7656ce9cdd89)

### Smartphone:
 - Device: Pixel 7 Pro
 - OS: GrapheneOS build 2024121200 (Android 15)
 - Browser: Vanadium (Chromium)
 - Version: 1.4.0 Beta

### Additional context / Contexte supplémentaire
Application used without gms/Google framework/ Google Play Services.

**Comment by camarm-dev** [comment]
Issue noted, this will be resolved in `1.4.0`. Thank you.

**Comment by Ilithy** [comment]
Thanks
