### ISSUE TITLE
⚡️ [Question] How will we serve mobile platforms like Android and iOS?

### ISSUE THREAD

**Issue by lbirkert** [camarm-dev/remede#61]
I am thrilled by this application, as I've always needed something opensource to replace the proprietary `dict.cc` android app we are allowed to use in french class. Although we seem to be using only VueJS currently, which let's me conclude that there will not be official native mobile applications for this service? How are you going about supporting this platform (as it is - at least for me - the most valuable for such)?

**Comment by camarm-dev** [comment]
Hi, thanks for your question !
Yes, the project seems to be developed in VueJS but it's actually developed with **IonicFramework** using a VueJS codebase:

- Ionic is "_An open source mobile UI toolkit for building modern, high quality cross-platform mobile apps from a single code base_" <sup>[their website](https://ionicframework.com/)</sup>.
- **Capacitor**<sup>[*](https://capacitorjs.com/)</sup> is "_A cross-platform native runtime for web apps_" developed by the Ionic Team, that permit our VueJs codebase to be served as a webview in a native application and it also permit to use native APIs using a _bridge_, right in our javascript code !

Ionic make the UI development easier for me and let me focus on functionalities. Capacitor make the distribution easier: Remède can build to APK, IPA or run on the web.

So, **yes**, the codebase can compile to an **APK** file (thanks to Capacitor !), downloadable in the [release section](https://github.com/camarm-dev/remede/releases).
Of course, my goal is to publish this on the **Play Store**.

I hope I'v answered your question,
Best regards,
Armand CAMPONOVO |  @camarm-dev

**Comment by lbirkert** [comment]
That's great news! I'll consider checking it out after it comes to Play Store or FDroid then.
